---
- name:     Install ViM
  package:
    name:   vim
    state:  present
  become: "{{ansible_system == 'Linux'}}"
  tags:
    - sudoed

- include_tasks: "{{ansible_os_family | lower}}.yml"

- name: Download Vundle
  git:  repo=https://github.com/gmarik/vundle.git
        dest=~/.vim/bundle/vundle

- name: Copy configs
  copy: src=config
        dest=~/.vim

- name: Copy vimrc
  copy: src=vimrc
        dest=~/.vimrc
        force=yes

- name:       Create file for local only configs
  lineinfile:
    create: yes
    dest:   "~/.vim/localconfig.vim"
    line:   "\" Intented for local only configurations"
    state:  present

- name:     Vundle it
  command:  vim +BundleInstall +qall

- name: Create dir for local history
  file:
    dest:   "{{ vim_machine.local_history_path }}"
    state:  directory

- name:   Create repo for local history
  shell:  git init
  args:
    chdir:    "{{ vim_machine.local_history_path }}"
    creates:  "{{ vim_machine.local_history_path }}/.git"
